### ISSUE TITLE
Questions about depth accuracy

### ISSUE THREAD

**Issue by LSXiang** [TongjiZhaohb/StereoCalibrator#4]
Hello, this is a very meaningful contribution. 

I have encountered the same problem in my own implementation of both the algorithm of this thesis and the “High-Precision Online Markerless Stereo Extrinsic Calibration” : The depth values solved after rectify the image with the self-calibration parameters are not as accurate as the depth values solved with the calibration board. Some of the disparity error is within 1 pixel. Do you have any suggestions?

I look forward to your reply.

**Comment by LSXiang** [comment]
I have one more question.
What is the significance of $e_0$ in Eq. 11 of the paper, and how should the information matrix of $e_0$ be defined if $e_i$ is defined in terms of pixel error, e.g., focal / 1. pixel.

**Comment by TongjiZhaohb** [comment]
Thank you for your question. Let me address the two issues in detail. First, regarding the problem of insufficient accuracy in stereo image rectification, my suggestion is to use a more robust matching algorithm, or to filter out outlier feature points during the process of solving the extrinsic parameters, as these can significantly affect the calibration results. Using the chessboard algorithm doesn't encounter this problem. Then, regarding  $e_0$ , it comes from equation (8) and is used to constrain the solution to our optimization problem, as you can see that  $r_{r,2}$  is orthogonal to  $i_3$ . When performing stereo rectification for a pair of cameras (left and right), the rectification result is not unique, and it is possible to get rectified images with poor viewing quality (e.g., images that are overly compressed). The purpose of  $e_0$  is to improve this issue.

**Comment by LSXiang** [comment]
Thank you for your answer.
